# Generated by Django 4.2.7 on 2024-01-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='customer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
