# Generated by Django 4.2.7 on 2024-01-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Username'),
        ),
    ]
